<?php
// This file is part of Moodle - http://moodle.org/
/**
 * Web service definitions for local_nexreports.
 *
 * @package    local_nexreports
 * @copyright  2026 Nex Academy
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_nexreports_get_summary' => [
        'classname' => 'local_nexreports\\external\\get_summary',
        'methodname' => 'execute',
        'description' => 'Overview KPIs, activity/visits charts, and tables',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_learner_headcount' => [
        'classname' => 'local_nexreports\\external\\get_learner_headcount',
        'methodname' => 'execute',
        'description' => 'Total students with institution and department breakdown',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_timespent_site' => [
        'classname' => 'local_nexreports\\external\\get_timespent_site',
        'methodname' => 'execute',
        'description' => 'Daily time spent on site with optional user filter',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_visits_site' => [
        'classname' => 'local_nexreports\\external\\get_visits_site',
        'methodname' => 'execute',
        'description' => 'Daily site visits with optional user filter',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_activity_status' => [
        'classname' => 'local_nexreports\\external\\get_activity_status',
        'methodname' => 'execute',
        'description' => 'Course activity status: submissions and completions by day',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_my_timespent' => [
        'classname' => 'local_nexreports\\external\\get_my_timespent',
        'methodname' => 'execute',
        'description' => 'Signed-in learner daily time spent on site',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_search_options' => [
        'classname' => 'local_nexreports\\external\\search_options',
        'methodname' => 'execute',
        'description' => 'Type-ahead search for user and course filter dropdowns',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_timespent_course' => [
        'classname' => 'local_nexreports\\external\\get_timespent_course',
        'methodname' => 'execute',
        'description' => 'Top courses by engaged time with optional filters',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_inactive_users' => [
        'classname' => 'local_nexreports\\external\\get_inactive_users',
        'methodname' => 'execute',
        'description' => 'Inactive learners list',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_daily_activity' => [
        'classname' => 'local_nexreports\\external\\get_daily_activity',
        'methodname' => 'execute',
        'description' => 'Daily activity totals for one calendar day',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_progress' => [
        'classname' => 'local_nexreports\\external\\get_course_progress',
        'methodname' => 'execute',
        'description' => 'Course progress average and distribution buckets',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_students_engagement' => [
        'classname' => 'local_nexreports\\external\\get_students_engagement',
        'methodname' => 'execute',
        'description' => 'All learner summary / student engagement table',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_learner_course_progress' => [
        'classname' => 'local_nexreports\\external\\get_learner_course_progress',
        'methodname' => 'execute',
        'description' => 'Learner course progress for a selected student',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_learner_course_activities' => [
        'classname' => 'local_nexreports\\external\\get_learner_course_activities',
        'methodname' => 'execute',
        'description' => 'Learner course activities for a selected student and course',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_portfolio_learners' => [
        'classname' => 'local_nexreports\\external\\get_portfolio_learners',
        'methodname' => 'execute',
        'description' => 'NexPortfolio learners connected to at least one platform',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_portfolio_github' => [
        'classname' => 'local_nexreports\\external\\get_portfolio_github',
        'methodname' => 'execute',
        'description' => 'NexPortfolio GitHub contribution and repository stats',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_practice_leaderboard' => [
        'classname' => 'local_nexreports\\external\\get_practice_leaderboard',
        'methodname' => 'execute',
        'description' => 'NexPractice XP leaderboard with solve counts and streaks',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_battle_leaderboard' => [
        'classname' => 'local_nexreports\\external\\get_battle_leaderboard',
        'methodname' => 'execute',
        'description' => 'NexBattleGround win leaderboard with battle XP',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_codelab_leaderboard' => [
        'classname' => 'local_nexreports\\external\\get_codelab_leaderboard',
        'methodname' => 'execute',
        'description' => 'NexCodeLab XP leaderboard with missions and solves',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_interview_attempts' => [
        'classname' => 'local_nexreports\\external\\get_interview_attempts',
        'methodname' => 'execute',
        'description' => 'NexInterview attempt ledger with scores and feedback links',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_courses_summary' => [
        'classname' => 'local_nexreports\\external\\get_courses_summary',
        'methodname' => 'execute',
        'description' => 'All courses summary for the Courses tab',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_activities_summary' => [
        'classname' => 'local_nexreports\\external\\get_course_activities_summary',
        'methodname' => 'execute',
        'description' => 'Course activities summary table',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_activity_completion' => [
        'classname' => 'local_nexreports\\external\\get_course_activity_completion',
        'methodname' => 'execute',
        'description' => 'Course activity completion table',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_quiz_cumulative' => [
        'classname' => 'local_nexreports\\external\\get_course_quiz_cumulative',
        'methodname' => 'execute',
        'description' => 'Cumulative quiz passed/failed/in-progress across all quizzes in a course',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_grades' => [
        'classname' => 'local_nexreports\\external\\get_course_grades',
        'methodname' => 'execute',
        'description' => 'Full course grades matrix by section and activity',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_course_completion' => [
        'classname' => 'local_nexreports\\external\\get_course_completion',
        'methodname' => 'execute',
        'description' => 'Course completion table',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_get_weekly_insights' => [
        'classname' => 'local_nexreports\\external\\get_weekly_insights',
        'methodname' => 'execute',
        'description' => 'Weekly learner improvement insights (8-week scorecards)',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_track_start' => [
        'classname' => 'local_nexreports\\external\\track_start',
        'methodname' => 'execute',
        'description' => 'Begin a dwell-time tracking window for the current page',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexreports_track_ping' => [
        'classname' => 'local_nexreports\\external\\track_ping',
        'methodname' => 'execute',
        'description' => 'Add measured seconds to a dwell-time tracking window',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
];
