<?php
defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_nexcomm_get_activities' => [
        'classname' => 'local_nexcomm\\external\\get_activities',
        'methodname' => 'execute',
        'description' => 'List NexComm activities',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_get_activity' => [
        'classname' => 'local_nexcomm\\external\\get_activity',
        'methodname' => 'execute',
        'description' => 'Get one activity for attempt',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_submit_attempt' => [
        'classname' => 'local_nexcomm\\external\\submit_attempt',
        'methodname' => 'execute',
        'description' => 'Submit an activity attempt',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_get_targets' => [
        'classname' => 'local_nexcomm\\external\\get_targets',
        'methodname' => 'execute',
        'description' => 'Daily and weekly targets',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_get_leaderboard' => [
        'classname' => 'local_nexcomm\\external\\get_leaderboard',
        'methodname' => 'execute',
        'description' => 'NexComm leaderboard',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_save_activity' => [
        'classname' => 'local_nexcomm\\external\\save_activity',
        'methodname' => 'execute',
        'description' => 'Create or update an activity',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_delete_activity' => [
        'classname' => 'local_nexcomm\\external\\delete_activity',
        'methodname' => 'execute',
        'description' => 'Delete an activity',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_list_manage' => [
        'classname' => 'local_nexcomm\\external\\list_manage',
        'methodname' => 'execute',
        'description' => 'List all activities for manage UI',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_get_lessons' => [
        'classname' => 'local_nexcomm\\external\\get_lessons',
        'methodname' => 'execute',
        'description' => 'List English Central-style video lessons',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_get_lesson' => [
        'classname' => 'local_nexcomm\\external\\get_lesson',
        'methodname' => 'execute',
        'description' => 'Get one video lesson',
        'type' => 'read',
        'ajax' => true,
        'loginrequired' => true,
    ],
    'local_nexcomm_save_lesson_progress' => [
        'classname' => 'local_nexcomm\\external\\save_lesson_progress',
        'methodname' => 'execute',
        'description' => 'Save Watch/Learn/Speak progress',
        'type' => 'write',
        'ajax' => true,
        'loginrequired' => true,
    ],
];
